disabled_rules:
- identifier_name
- todo
- type_body_length
- line_length
- cyclomatic_complexity
- nesting
- file_length
- function_body_length
- implicitly_unwrapped_optional

opt_in_rules:
- attributes
- closure_end_indentation
- closure_spacing
- collection_alignment
- contains_over_first_not_nil
- explicit_init
- extension_access_modifier
- fallthrough
- fatal_error_message
- first_where
- function_default_parameter_at_end
- identical_operands
- implicit_return
- implicitly_unwrapped_optional
- joined_default_parameter
- last_where
- legacy_random
- literal_expression_end_indentation
- lower_acl_than_parent
- modifier_order
- multiline_arguments
- multiline_arguments_brackets
- multiline_literal_brackets
- multiline_parameters
- multiline_parameters_brackets
- operator_usage_whitespace
- overridden_super_call
- redundant_nil_coalescing
- redundant_type_annotation
- trailing_closure
- unavailable_function
- unneeded_parentheses_in_closure_argument
- vertical_whitespace_opening_braces
- vertical_whitespace_closing_braces
- yoda_condition

excluded:
- Pods/
- Carthage/
- vendor/
